module.exports = {
  env: {
    API_KEY : process.env.API_KEY,
    AUTH_DOMAIN : process.env.AUTH_DOMAIN,
    DATABASE_URL: process.env.DATABASE_URL,
    PROJECT_ID: process.env.PROJECT_ID,
    STORAGE_BUCKET: process.env.STORAGE_BUCKET,
    MESSAGING_SENDER_ID: process.env.MESSAGING_SENDER_ID,
    APP_ID: process.env.APP_ID,
    TEST_VAR: process.env.TEST_VAR,
    SERVICE_TYPE: process.env.SERVICE_TYPE,
    SERVICE_PROJECT_ID: process.env.SERVICE_PROJECT_ID,
    SERVICE_PRIVATE_KEY_ID: process.env.SERVICE_PRIVATE_KEY_ID,
    SERVICE_PRIVATE_KEY: process.env.SERVICE_PRIVATE_KEY,
    SERVICE_CLIENT_EMAIL: process.env.SERVICE_CLIENT_EMAIL,
    SERVICE_CLIENT_ID: process.env.SERVICE_CLIENT_ID,
    SERVICE_AUTH_URI: process.env.SERVICE_AUTH_URI,
    SERVICE_TOKEN_URI: process.env.SERVICE_TOKEN_URI,
    SERVICE_AUTH_PROVIDER_X509_CERT_URL: process.env.SERVICE_AUTH_PROVIDER_X509_CERT_URL,
    SERVICE_CLIENT_X509_CERT_URL: process.env.SERVICE_CLIENT_X509_CERT_URL
  },
};